### ISSUE TITLE
Attempting to upgrade database during read fails

### ISSUE THREAD

**Issue by Alexander--** [hamsterksu/Android-AnnotatedSQL#14]
This isn't strictly speaking an issue with Android-AnnotatedSQL, but it can be sort-of worked around on ContentProvider level, so I am bringing it to your attention now:
```
android.database.sqlite.SQLiteException: Can't downgrade database from version 10 to 9
            at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:307)
            at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:168)
            at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:231)
            at com.example.ExampleProviderProto.query(ExampleProviderProto.java:148)
```
The cause is [the default SQLiteOpenHelper](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/database/sqlite/SQLiteOpenHelper.java). It looks rather funny, if you consider, that according to comments at the top of source file getReadableDatabase over getWritableDatabase doesn't make any difference in production OS builds.

**Comment by Alexander--** [comment]
Wasn't able to reproduce that again. I guess, this should be closed.
